apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: ecommerce-dev
spec:
  selector:
    matchLabels:
      app: user-service

  namespaceSelector:
    matchNames:
      - ecommerce-dev

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s